gap = 8
border_width = 2
border_color = "#444444"
border_focus_color = "#8888ff"
master_ratio = 0.5
terminal = "kitty"

autostart = [
    "picom --daemon",
    "feh --bg-fill /home/vapma/.walls/53db35e5cb12dd475517003dbf72440b.jpg ",
    "nm-applet --indicator",
    "blueman-applet",
    "polybar",
]

[keybinds]
close_window = "super+q"
quit = "super+shift+q"
swap_master = "super+w"
focus_next = "super+j"
focus_prev = "super+k"
terminal = "super+return"
restart = "super+shift+r"
workspace_switch = "super"
workspace_move = "super+shift"

[bar]
enabled = false

[[custom_keys]]
binding = "super+b"
action = "exec"
arg = "brave"

[[custom_keys]]
binding = "super+space"
action = "exec"
arg = "rofi -show run"
